# Generated by Django 4.2 on 2023-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок записи')),
                ('content', models.TextField(verbose_name='Содержание записи')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания публикации')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
